# Generated by Django 3.2.15 on 2023-05-06 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assay', '0004_auto_20230506_0730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='votes_true',
        ),
    ]
